### ISSUE TITLE
How to bring Template working in the 2019-Jan version of development tools, into new version

### ISSUE THREAD

**Issue by ryansena** [OpenCerts/admin-website#102]
We have created and tested OK a template name SP2019MAIN using the development tools in Jan 2019.
the template reside in folder <oldver>\src\components\CertificateTemplates\sg\edu\sp

We are now using the newer version of the development tools, we copied the sp folder into:
<newver>\src\components\CertificateTemplates\tlds\sg\edu\sp
and added 'sp' to the index.js in the parent folder
it compile Okay.  BUT the template is not effective, the default template is used instead of the SP2019MAIN template.

where did i miss doing something ?  Please help

**Comment by yehjxraymond** [comment]
Hi we are migrating all the templates to a separate repo now, could you:
1. Fork the new template repo (https://github.com/OpenCerts/legacy-templates)
2. Perform the changes and then create a pull request to us. We will take a look at what went wrong. 

P.s. to test, you can copy your certificate (before batching) into the index.html located at (/test/index.html) in that repository. 

So you will run that repo with `npm run dev` and then open the index.html in the test folder to test. To test with your school's certificate, replace line54 of index.html with your school's certificate.

**Comment by ryansena** [comment]
done pushing to ur side, via sp-cert branch.

**Comment by yehjxraymond** [comment]
We did not see any pull request, make sure you have a pull request to us.

**Comment by ryansena** [comment]
please check again

**Comment by yehjxraymond** [comment]
Still don’t see any pr. Please make sure the PR is merging into our repo. Also copy the PR link here once you’ve create it pls.

**Comment by ryansena** [comment]
That's weird did PR yesterday:
PS C:\GovTech\OpenCert_Site\Legacy\legacy-templates\src\components\CertificateTemplates\tlds\sg\edu\sp> git pull upstream master
From https://github.com/OpenCerts/legacy-templates
 * branch            master     -> FETCH_HEAD
 * [new branch]      master     -> upstream/master
Already up to date.

PS C:\GovTech\OpenCert_Site\Legacy\legacy-templates\src\components\CertificateTemplates\tlds\sg\edu\sp> git commit --no-verify
[master e294c51]        new file:   SP-2019-MAIN/Certimages.js  new file:   SP-2019-MAIN/certificate.js         new file:   SP-2019-MAIN/images.js      new file:   SP-2019-MAIN/index.js
new file:   SP-2019-MAIN/resources.js   new file:   SP-2019-MAIN/transcript.js  new file:   index.js    modified:   ../index.js
 27 files changed, 2744 insertions(+)
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/sp/SP-2019-MAIN/Certimages.js
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/sp/SP-2019-MAIN/certificate.js
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/sp/SP-2019-MAIN/certificate_20190130.js
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/sp/SP-2019-MAIN/certificate_yu2.js
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/sp/SP-2019-MAIN/certificate_yu3 - Copy (2).js
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/sp/SP-2019-MAIN/certificate_yu3 - Copy.js
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/sp/SP-2019-MAIN/certificate_yu3.js
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/sp/SP-2019-MAIN/certificate_yu3Copy7mockup.js
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/sp/SP-2019-MAIN/images.js
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/sp/SP-2019-MAIN/index.js
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/sp/SP-2019-MAIN/index.zip
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/sp/SP-2019-MAIN/indexCopy2mockup.js
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/sp/SP-2019-MAIN/index_0.js
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/sp/SP-2019-MAIN/index_copy1.js
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/sp/SP-2019-MAIN/resources.js
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/sp/SP-2019-MAIN/transcript - Copy.js
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/sp/SP-2019-MAIN/transcript.js
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/sp/SP-2019-MAIN/transcript_yu.js
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/sp/SP-2019-MAIN/transcript_yu2.js
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/sp/SP-2019-MAIN/transcript_yuCopy2.js
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/sp/SP-2019-MAIN/transcript_yuCopy3.js
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/sp/SP-2019-MAIN/transcript_yuCopy4.js
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/sp/SP-2019-MAIN/transcript_yuCopy5.js
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/sp/SP-2019-MAIN/transcript_yuCopy6.js
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/sp/SP-2019-MAIN/transcript_yuCopy7.js
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/sp/SP-2019-MAIN/transcript_yuCopy8mockup.js
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/sp/index.js
PS C:\GovTech\OpenCert_Site\Legacy\legacy-templates\src\components\CertificateTemplates\tlds\sg\edu\sp> git push --no-verify
Username for 'https://github.com': ryansena
Password for 'https://ryansena@github.com':
Enumerating objects: 41, done.
Counting objects: 100% (41/41), done.
Delta compression using up to 4 threads
Compressing objects: 100% (34/34), done.
Writing objects: 100% (34/34), 271.84 KiB | 12.36 MiB/s, done.
Total 34 (delta 17), reused 0 (delta 0)
remote: Resolving deltas: 100% (17/17), completed with 4 local objects.
To https://github.com/ryansena/legacy-templates
   fe27a4d..e294c51  master -> master
PS C:\GovTech\OpenCert_Site\Legacy\legacy-templates\src\components\CertificateTemplates\tlds\sg\edu\sp>

**Comment by yehjxraymond** [comment]
There is no PR there. You need to fork and then create a PR form your repo to ours

**Comment by ryansena** [comment]
Sorry, is this correct?
https://github.com/OpenCerts/legacy-templates/commit/e294c51480922c3787b9d5bcebb9dbd49fe61084

**Comment by yehjxraymond** [comment]
Hi, that is not creating a PR to us, if you have done it correctly, you will be able to see it here: https://github.com/OpenCerts/legacy-templates/pulls.

Please search for how  to create a pull request. You may also read: https://git-scm.com/book/en/v2/GitHub-Contributing-to-a-Project

**Comment by ryansena** [comment]
created the PR in OpenCerts/legacy-templates#10
